pub mod almanac;
pub mod calibration;
pub mod camelcard;
pub mod camelcard2;
pub mod cube_game;
pub mod desert;
pub mod engine_schematic;
mod grid2d;
pub mod hash;
pub mod hotsprings;
pub mod oasis;
pub mod observatory;
pub mod pipe;
pub mod race;
pub mod reflection;
pub mod rocks;
pub mod scratchcard;
